name: CI

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v4

      - name: Instalar JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: "11"
          distribution: "microsoft"

      - name: Construir con Maven
        run: mvn clean package -DskipTests

      - name: Guardar paquete generado
        uses: actions/upload-artifact@v4
        with:
          name: moviecards-java
          path: "target/*.jar"

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v4

      - name: Instalar JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: "11"
          distribution: "microsoft"

      - name: Instalar Chrome y ChromeDriver
        run: |
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo dpkg -i google-chrome-stable_current_amd64.deb
          sudo apt --fix-broken install -y
          CHROMEDRIVER_VERSION=$(curl -sS https://chromedriver.storage.googleapis.com/LATEST_RELEASE)
          curl -L -o chromedriver.zip https://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION/chromedriver_linux64.zip
          unzip chromedriver.zip
          chmod +x chromedriver
          sudo mv chromedriver /usr/local/bin/

      - name: Ejecutar la aplicación y pruebas
        run: |
          mvn spring-boot:run & sleep 60
          mvn clean verify

  qa:
    needs: test
    runs-on: self-hosted
    continue-on-error: true
    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v4
      - name: Revisar la calidad con Sonarqube
        run: |
          mvn sonar:sonar -Dsonar.host.url=http://localhost:9000 -Dsonar.qualitygate.wait=false -Dsonar.login=admin -Dsonar.password=juan || true

  deploy:
    runs-on: ubuntu-latest
    needs: qa
    # PERMISOS CRÍTICOS PARA LA APROBACIÓN MANUAL
    permissions:
      issues: write
      contents: read
    # Se ejecuta en main o master aunque falle el QA previo
    if: always() && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master')
    
    steps:
      - name: Aprobación manual
        uses: trstringer/manual-approval@v1
        with:
          secret: ${{ secrets.GITHUB_TOKEN }}
          approvers: JuanHigueroL

      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: moviecards-java

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'moviecards-higuero'
          slot-name: 'Production'
          package: '*.jar'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_AD04F98D697743958B5CC12F474FE188 }}